"use client";
import {useState} from "react";
import type {AdminData,Project} from "@/lib/admin-types";
import {parseMap} from "@/lib/admin-types";
import {areaLabel,services} from "@/lib/operations";
import MapPreview from "@/app/components/MapPreview";
import ProjectsMap from "./ProjectsMap";
export default function MapLibrary({data,onOpen,onMap,onCreate,onRemove,onEstimate}:{data:AdminData;onOpen:(p:Project)=>void;onMap:(p:Project)=>void;onCreate:(clientId?:string)=>void;onRemove:(p:Project)=>Promise<void>;onEstimate:(p:Project)=>void}) {
  const [service,setService]=useState(""),[folder,setFolder]=useState(""),[busy,setBusy]=useState("");
  const mapped=data.projects.filter(p=>parseMap(p)&&(!service||p.serviceType===service)&&(!folder||p.clientId===folder));
  return <section aria-label="Map library"><div className="map-overview-controls"><button className="admin-save" onClick={()=>onCreate(folder||undefined)}>＋ Create mapped location</button><label><span className="sr-only">Map service</span><select value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{Object.entries(services).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label><span className="sr-only">Client folder</span><select value={folder} onChange={e=>setFolder(e.target.value)}><option value="">All client folders</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label></div>
    <ProjectsMap projects={mapped} clients={data.clients} onOpen={onOpen}/><div className="map-service-legend"><span>🌾 Prairie / wildflower plot</span><span>🌿 Native landscape</span><span>◎ Consultation</span></div><p>{mapped.length} saved locations · Select a pin to open its project, client and planting notebook.</p>
    <div className="map-folders">{data.clients.filter(c=>(!folder||c.id===folder)&&mapped.some(p=>p.clientId===c.id)).map(c=><details className="map-folder" key={c.id} open><summary>{c.firstName} {c.lastName} · {mapped.filter(p=>p.clientId===c.id).length} locations</summary><div className="record-actions"><button onClick={()=>onCreate(c.id)}>＋ Add location to folder</button></div><div className="project-grid">{mapped.filter(p=>p.clientId===c.id).map(p=>{const map=parseMap(p)!;return <article className="project-card" key={p.id}><MapPreview map={map} title={p.name}/><div className="project-card-body"><p className="admin-kicker">{services[p.serviceType as keyof typeof services]}</p><h2>{p.name}</h2><p>{p.siteAddress}</p>{map.features.filter(f=>f.kind==="area").map(f=><div className="map-location-area" key={f.id}><strong>{f.title} · {areaLabel(f.points)}</strong>{f.plants&&<p>{f.plants}</p>}{f.notes&&<p>{f.notes}</p>}</div>)}<p className="field-hint">{data.projectItems.filter(i=>i.projectId===p.id&&!i.archived).map(i=>i.name).join(" · ")||"No project items yet"}</p><div className="record-actions"><button onClick={()=>onOpen(p)}>Open project & client</button><button onClick={()=>onMap(p)}>Edit map</button><button onClick={()=>onEstimate(p)}>Use in estimate</button><button disabled={!!busy} onClick={async()=>{if(!confirm("Remove this saved map? The project, items and existing estimate attachments will be kept."))return;setBusy(p.id);try{await onRemove(p);}finally{setBusy("");}}}>{busy===p.id?"Removing…":"Remove map"}</button></div></div></article>;})}</div></details>)}</div>
    {!mapped.length&&<p className="office-empty">No saved maps in this view. Create a mapped location or choose another folder.</p>}
  </section>;
}
